// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crypto-schema/outer_payload.proto
// Protobuf Java Version: 4.34.1

package com.nodes.chatclient.e2ee.protos;

@com.google.protobuf.Generated
public final class ProtoOuterPayload extends com.google.protobuf.GeneratedFile {
  private ProtoOuterPayload() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ProtoOuterPayload");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OuterPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OuterPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fromUserId = 1;</code>
     * @return The fromUserId.
     */
    java.lang.String getFromUserId();
    /**
     * <code>string fromUserId = 1;</code>
     * @return The bytes for fromUserId.
     */
    com.google.protobuf.ByteString
        getFromUserIdBytes();

    /**
     * <code>string fromDeviceId = 2;</code>
     * @return The fromDeviceId.
     */
    java.lang.String getFromDeviceId();
    /**
     * <code>string fromDeviceId = 2;</code>
     * @return The bytes for fromDeviceId.
     */
    com.google.protobuf.ByteString
        getFromDeviceIdBytes();

    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    java.lang.String getToUserId();
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    com.google.protobuf.ByteString
        getToUserIdBytes();

    /**
     * <code>string toDeviceId = 4;</code>
     * @return The toDeviceId.
     */
    java.lang.String getToDeviceId();
    /**
     * <code>string toDeviceId = 4;</code>
     * @return The bytes for toDeviceId.
     */
    com.google.protobuf.ByteString
        getToDeviceIdBytes();

    /**
     * <code>bytes dhPublicKey = 5;</code>
     * @return The dhPublicKey.
     */
    com.google.protobuf.ByteString getDhPublicKey();

    /**
     * <code>uint64 messageNumber = 6;</code>
     * @return The messageNumber.
     */
    long getMessageNumber();

    /**
     * <code>uint64 previousChainLength = 7;</code>
     * @return The previousChainLength.
     */
    long getPreviousChainLength();

    /**
     * <code>bytes iv = 8;</code>
     * @return The iv.
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes ciphertext = 9;</code>
     * @return The ciphertext.
     */
    com.google.protobuf.ByteString getCiphertext();

    /**
     * <code>bytes signature = 10;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code OuterPayload}
   */
  public static final class OuterPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OuterPayload)
      OuterPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "OuterPayload");
    }
    // Use OuterPayload.newBuilder() to construct.
    private OuterPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OuterPayload() {
      fromUserId_ = "";
      fromDeviceId_ = "";
      toUserId_ = "";
      toDeviceId_ = "";
      dhPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      iv_ = com.google.protobuf.ByteString.EMPTY;
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.class, com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.Builder.class);
    }

    public static final int FROMUSERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fromUserId_ = "";
    /**
     * <code>string fromUserId = 1;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public java.lang.String getFromUserId() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromUserId = 1;</code>
     * @return The bytes for fromUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMDEVICEID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fromDeviceId_ = "";
    /**
     * <code>string fromDeviceId = 2;</code>
     * @return The fromDeviceId.
     */
    @java.lang.Override
    public java.lang.String getFromDeviceId() {
      java.lang.Object ref = fromDeviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromDeviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromDeviceId = 2;</code>
     * @return The bytes for fromDeviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromDeviceIdBytes() {
      java.lang.Object ref = fromDeviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUSERID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toUserId_ = "";
    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public java.lang.String getToUserId() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TODEVICEID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toDeviceId_ = "";
    /**
     * <code>string toDeviceId = 4;</code>
     * @return The toDeviceId.
     */
    @java.lang.Override
    public java.lang.String getToDeviceId() {
      java.lang.Object ref = toDeviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toDeviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string toDeviceId = 4;</code>
     * @return The bytes for toDeviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToDeviceIdBytes() {
      java.lang.Object ref = toDeviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DHPUBLICKEY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString dhPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes dhPublicKey = 5;</code>
     * @return The dhPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDhPublicKey() {
      return dhPublicKey_;
    }

    public static final int MESSAGENUMBER_FIELD_NUMBER = 6;
    private long messageNumber_ = 0L;
    /**
     * <code>uint64 messageNumber = 6;</code>
     * @return The messageNumber.
     */
    @java.lang.Override
    public long getMessageNumber() {
      return messageNumber_;
    }

    public static final int PREVIOUSCHAINLENGTH_FIELD_NUMBER = 7;
    private long previousChainLength_ = 0L;
    /**
     * <code>uint64 previousChainLength = 7;</code>
     * @return The previousChainLength.
     */
    @java.lang.Override
    public long getPreviousChainLength() {
      return previousChainLength_;
    }

    public static final int IV_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes iv = 8;</code>
     * @return The iv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int CIPHERTEXT_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ciphertext = 9;</code>
     * @return The ciphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature = 10;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromUserId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, fromUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromDeviceId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, fromDeviceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toUserId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, toUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toDeviceId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, toDeviceId_);
      }
      if (!dhPublicKey_.isEmpty()) {
        output.writeBytes(5, dhPublicKey_);
      }
      if (messageNumber_ != 0L) {
        output.writeUInt64(6, messageNumber_);
      }
      if (previousChainLength_ != 0L) {
        output.writeUInt64(7, previousChainLength_);
      }
      if (!iv_.isEmpty()) {
        output.writeBytes(8, iv_);
      }
      if (!ciphertext_.isEmpty()) {
        output.writeBytes(9, ciphertext_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(10, signature_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromUserId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fromUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromDeviceId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, fromDeviceId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toUserId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, toUserId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(toDeviceId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, toDeviceId_);
      }
      if (!dhPublicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, dhPublicKey_);
      }
      if (messageNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, messageNumber_);
      }
      if (previousChainLength_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, previousChainLength_);
      }
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, iv_);
      }
      if (!ciphertext_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, ciphertext_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, signature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload)) {
        return super.equals(obj);
      }
      com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload other = (com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload) obj;

      if (!getFromUserId()
          .equals(other.getFromUserId())) return false;
      if (!getFromDeviceId()
          .equals(other.getFromDeviceId())) return false;
      if (!getToUserId()
          .equals(other.getToUserId())) return false;
      if (!getToDeviceId()
          .equals(other.getToDeviceId())) return false;
      if (!getDhPublicKey()
          .equals(other.getDhPublicKey())) return false;
      if (getMessageNumber()
          != other.getMessageNumber()) return false;
      if (getPreviousChainLength()
          != other.getPreviousChainLength()) return false;
      if (!getIv()
          .equals(other.getIv())) return false;
      if (!getCiphertext()
          .equals(other.getCiphertext())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId().hashCode();
      hash = (37 * hash) + FROMDEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getFromDeviceId().hashCode();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
      hash = (37 * hash) + TODEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getToDeviceId().hashCode();
      hash = (37 * hash) + DHPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getDhPublicKey().hashCode();
      hash = (37 * hash) + MESSAGENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageNumber());
      hash = (37 * hash) + PREVIOUSCHAINLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPreviousChainLength());
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getCiphertext().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OuterPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OuterPayload)
        com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.class, com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.Builder.class);
      }

      // Construct using com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fromUserId_ = "";
        fromDeviceId_ = "";
        toUserId_ = "";
        toDeviceId_ = "";
        dhPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        messageNumber_ = 0L;
        previousChainLength_ = 0L;
        iv_ = com.google.protobuf.ByteString.EMPTY;
        ciphertext_ = com.google.protobuf.ByteString.EMPTY;
        signature_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.internal_static_OuterPayload_descriptor;
      }

      @java.lang.Override
      public com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload getDefaultInstanceForType() {
        return com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.getDefaultInstance();
      }

      @java.lang.Override
      public com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload build() {
        com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload buildPartial() {
        com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload result = new com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromUserId_ = fromUserId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fromDeviceId_ = fromDeviceId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.toUserId_ = toUserId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.toDeviceId_ = toDeviceId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dhPublicKey_ = dhPublicKey_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.messageNumber_ = messageNumber_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.previousChainLength_ = previousChainLength_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.iv_ = iv_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.ciphertext_ = ciphertext_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.signature_ = signature_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload) {
          return mergeFrom((com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload other) {
        if (other == com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload.getDefaultInstance()) return this;
        if (!other.getFromUserId().isEmpty()) {
          fromUserId_ = other.fromUserId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFromDeviceId().isEmpty()) {
          fromDeviceId_ = other.fromDeviceId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getToUserId().isEmpty()) {
          toUserId_ = other.toUserId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getToDeviceId().isEmpty()) {
          toDeviceId_ = other.toDeviceId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getDhPublicKey().isEmpty()) {
          setDhPublicKey(other.getDhPublicKey());
        }
        if (other.getMessageNumber() != 0L) {
          setMessageNumber(other.getMessageNumber());
        }
        if (other.getPreviousChainLength() != 0L) {
          setPreviousChainLength(other.getPreviousChainLength());
        }
        if (!other.getIv().isEmpty()) {
          setIv(other.getIv());
        }
        if (!other.getCiphertext().isEmpty()) {
          setCiphertext(other.getCiphertext());
        }
        if (!other.getSignature().isEmpty()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fromUserId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                fromDeviceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                toUserId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                toDeviceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                dhPublicKey_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                messageNumber_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                previousChainLength_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                iv_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                ciphertext_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                signature_ = input.readBytes();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fromUserId_ = "";
      /**
       * <code>string fromUserId = 1;</code>
       * @return The fromUserId.
       */
      public java.lang.String getFromUserId() {
        java.lang.Object ref = fromUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromUserId = 1;</code>
       * @return The bytes for fromUserId.
       */
      public com.google.protobuf.ByteString
          getFromUserIdBytes() {
        java.lang.Object ref = fromUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromUserId = 1;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fromUserId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        fromUserId_ = getDefaultInstance().getFromUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 1;</code>
       * @param value The bytes for fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromUserId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object fromDeviceId_ = "";
      /**
       * <code>string fromDeviceId = 2;</code>
       * @return The fromDeviceId.
       */
      public java.lang.String getFromDeviceId() {
        java.lang.Object ref = fromDeviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromDeviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromDeviceId = 2;</code>
       * @return The bytes for fromDeviceId.
       */
      public com.google.protobuf.ByteString
          getFromDeviceIdBytes() {
        java.lang.Object ref = fromDeviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromDeviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromDeviceId = 2;</code>
       * @param value The fromDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setFromDeviceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fromDeviceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string fromDeviceId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromDeviceId() {
        fromDeviceId_ = getDefaultInstance().getFromDeviceId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string fromDeviceId = 2;</code>
       * @param value The bytes for fromDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setFromDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromDeviceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object toUserId_ = "";
      /**
       * <code>string toUserId = 3;</code>
       * @return The toUserId.
       */
      public java.lang.String getToUserId() {
        java.lang.Object ref = toUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return The bytes for toUserId.
       */
      public com.google.protobuf.ByteString
          getToUserIdBytes() {
        java.lang.Object ref = toUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toUserId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        toUserId_ = getDefaultInstance().getToUserId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The bytes for toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toUserId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object toDeviceId_ = "";
      /**
       * <code>string toDeviceId = 4;</code>
       * @return The toDeviceId.
       */
      public java.lang.String getToDeviceId() {
        java.lang.Object ref = toDeviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toDeviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toDeviceId = 4;</code>
       * @return The bytes for toDeviceId.
       */
      public com.google.protobuf.ByteString
          getToDeviceIdBytes() {
        java.lang.Object ref = toDeviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toDeviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toDeviceId = 4;</code>
       * @param value The toDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setToDeviceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toDeviceId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string toDeviceId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToDeviceId() {
        toDeviceId_ = getDefaultInstance().getToDeviceId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string toDeviceId = 4;</code>
       * @param value The bytes for toDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setToDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toDeviceId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dhPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes dhPublicKey = 5;</code>
       * @return The dhPublicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDhPublicKey() {
        return dhPublicKey_;
      }
      /**
       * <code>bytes dhPublicKey = 5;</code>
       * @param value The dhPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setDhPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        dhPublicKey_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes dhPublicKey = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDhPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dhPublicKey_ = getDefaultInstance().getDhPublicKey();
        onChanged();
        return this;
      }

      private long messageNumber_ ;
      /**
       * <code>uint64 messageNumber = 6;</code>
       * @return The messageNumber.
       */
      @java.lang.Override
      public long getMessageNumber() {
        return messageNumber_;
      }
      /**
       * <code>uint64 messageNumber = 6;</code>
       * @param value The messageNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMessageNumber(long value) {

        messageNumber_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 messageNumber = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageNumber() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageNumber_ = 0L;
        onChanged();
        return this;
      }

      private long previousChainLength_ ;
      /**
       * <code>uint64 previousChainLength = 7;</code>
       * @return The previousChainLength.
       */
      @java.lang.Override
      public long getPreviousChainLength() {
        return previousChainLength_;
      }
      /**
       * <code>uint64 previousChainLength = 7;</code>
       * @param value The previousChainLength to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousChainLength(long value) {

        previousChainLength_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 previousChainLength = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousChainLength() {
        bitField0_ = (bitField0_ & ~0x00000040);
        previousChainLength_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 8;</code>
       * @return The iv.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 8;</code>
       * @param value The iv to set.
       * @return This builder for chaining.
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        iv_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIv() {
        bitField0_ = (bitField0_ & ~0x00000080);
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ciphertext = 9;</code>
       * @return The ciphertext.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCiphertext() {
        return ciphertext_;
      }
      /**
       * <code>bytes ciphertext = 9;</code>
       * @param value The ciphertext to set.
       * @return This builder for chaining.
       */
      public Builder setCiphertext(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ciphertext_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ciphertext = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCiphertext() {
        bitField0_ = (bitField0_ & ~0x00000100);
        ciphertext_ = getDefaultInstance().getCiphertext();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 10;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 10;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        signature_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000200);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OuterPayload)
    }

    // @@protoc_insertion_point(class_scope:OuterPayload)
    private static final com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload();
    }

    public static com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OuterPayload>
        PARSER = new com.google.protobuf.AbstractParser<OuterPayload>() {
      @java.lang.Override
      public OuterPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OuterPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OuterPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nodes.chatclient.e2ee.protos.ProtoOuterPayload.OuterPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OuterPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OuterPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!crypto-schema/outer_payload.proto\"\332\001\n\014" +
      "OuterPayload\022\022\n\nfromUserId\030\001 \001(\t\022\024\n\014from" +
      "DeviceId\030\002 \001(\t\022\020\n\010toUserId\030\003 \001(\t\022\022\n\ntoDe" +
      "viceId\030\004 \001(\t\022\023\n\013dhPublicKey\030\005 \001(\014\022\025\n\rmes" +
      "sageNumber\030\006 \001(\004\022\033\n\023previousChainLength\030" +
      "\007 \001(\004\022\n\n\002iv\030\010 \001(\014\022\022\n\nciphertext\030\t \001(\014\022\021\n" +
      "\tsignature\030\n \001(\014B5\n com.nodes.chatclient" +
      ".e2ee.protosB\021ProtoOuterPayloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OuterPayload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_OuterPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OuterPayload_descriptor,
        new java.lang.String[] { "FromUserId", "FromDeviceId", "ToUserId", "ToDeviceId", "DhPublicKey", "MessageNumber", "PreviousChainLength", "Iv", "Ciphertext", "Signature", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
